### ISSUE TITLE
Random Bug

### ISSUE THREAD

**Issue by VaclavVal** [lofcz/SimplexRpgEngine#10]
Při testování Enginu, konkrétně při spellech došlo po zmáčknutí klávesy "J" k následujícímu erroru:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object oHUD:

**undefined value
 at gml_Script_scrAffectsUpdate (line 81) -       draw_ring_part(xxx, yyy, 16*scale, 4, 64, 64, 90, (oPlayer.statusTimeList[| i] / time) * 360, true, oPlayer.statusColorList[| i], true);** 
############################################################################################
stack frame is
gml_Script_scrAffectsUpdate (line 81)
called from - gml_Object_oHUD_DrawEvent_1 (line 9) - scrAffectsUpdate();

Nejsem si jistý, kdy přesně se toto děje, ale když narážím do slimáků a u toho používám spell "J" tak se občas stane, že se toto napíše...

**Comment by lofcz** [comment]
**Reprodukováno v RED verzi.** 
Ds_ struktury se chovají v okamžiku zničení jedné dost nevypočitatelně, zkusím implementovat c++ smart pointers.

**Comment by lofcz** [comment]
K chybě dojde v okamžiku, kdy při zničení jednoho stacku přidám nový, aplikuji vynucené castění na int32 a kontrolu pointeru via is_undefined.

**Comment by lofcz** [comment]
Vyřešeno v commitu 190
