### ISSUE TITLE
Odhozená věc nelze znovu vzít

### ISSUE THREAD

**Issue by VaclavVal** [lofcz/SimplexRpgEngine#12]
Při odhození libovolné věci na zem, tak po ovpětovném pokusu o sebrání odhozeného předmětu (při kolizi s odhozeným předmětem) dojde k chybě:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step EventoPlayer
for object oBasicItem:

Push :: Execution Error - Variable Get 100289.itm_materialType(100252, -2147483648)
 at gml_Script_inventoryPickUpParam (line 39) - oInventory.slot[free_slot,inv_item_materialType]      = itm_materialType;
############################################################################################
stack frame is
gml_Script_inventoryPickUpParam (line 39)
called from - gml_Script_inventoryPickUp (line 53) -             inventoryPickUpParam(1);                                                                              
called from - gml_Object_oBasicItem_CollisionEvent_0_1 (line 3) - inventoryPickUp();

**Comment by VaclavVal** [comment]
Po upuštění předmětu se po pravděpodobně nenastaví _inv_id_, tedy **itm_materialType**. Rád bych, kdyby ses na to podíval @lofcz

**Comment by lofcz** [comment]
Ve skript **scrInventoryDrop** se nenastavila proměnná **itm_materialType**. Opraveno v commitu 195.
