### ISSUE TITLE
Kouzlo "L" dává poškození i přes překážky

### ISSUE THREAD

**Issue by VaclavVal** [lofcz/SimplexRpgEngine#13]
Při použití ohnivého kouzla " L " před kamenem, pařezem, či stromem se particle efekt zastaví o překážku, zatímco "paprsek poškození" putuje dál a zraní tak slimáka, který se za překážkou nachází:
https://s32.postimg.org/sxi0qqget/Simplex.png
Pokusím se to nějak pořešit, popř. žádám o vyřešení @lofcz

**Comment by lofcz** [comment]
Objekt **oLenghtdirSpellhelper** se nyní ničí při kolizi s potomky prefabu parSolid. Opraveno v commitu 195. Další testy v této oblasti jsou vhodné. Zatím považuji za vyřešené, v případě nestabilního chování **reopen**.
