### ISSUE TITLE
Port Simplexu pro LGM

### ISSUE THREAD

**Issue by lofcz** [lofcz/SimplexRpgEngine#17]

**Comment by lofcz** [comment]
**Komunitní projekt uzavřen jako neaktivní**
Na žádost autora může být znovu otevřeno.

**Comment by lofcz** [comment]
*Na žádost autora znovu otevřeno*

**Comment by OpravdovyKvejk** [comment]
A few compromises will have to be made, including a limit regarding the number of sprites a project has. If the number of sprites exceeds this limit, LGM will not load the project, returning a "sprite header" error instead. LGM's limitations will also have to be accounted for (such as the absence of tabs and bookmarks in the LGM code editor).

**Comment by lofcz** [comment]
@OpravdovyKvejk Can you be more exact about sprite count limitation? Is this lgm or enigma problem? Im the other case, I would recommend you to get in touch with IsmAvatar as he can fix this issue. I will later confirm reproducibilty of this issue, as I am not aware of any lgm resources limit. Having this limitation is against idea of the Simplex RPG Engine and it is not going to be merged into the official branch in pre-dev timeframe. Script tabs are standardized part of the SimplexSyntaxConventions. Here, the best solution is to write wrapper of the Simplex RPG Engine which will parse Simplex GMX files into LGM compactible equivalent. Since wrappers are officialy supported, this can be merged into the core branch. Also, we are providing our own IDE, so lgm does not have to be supported at any cost. Therefore, priority is to achieve compatibility with the Enigma compiler.

**Comment by OpravdovyKvejk** [comment]
If we're creating our own IDE, why bother making an LGM port?
The sprite limit seems to be an LGM problem, as the IDE is unable to handle the amount of sprites Simplex currently ships with. The compiler should not have a problem, but, again, the issue of tabs being unsupported is stopping us from compiling with Enigma. This could be solved by the custom IDE storing tabs as some sort of folders, which could then be read by Engima.
Getting into contact with IsmAvatar would seem wise would it not be for the fact that he doesn't work on the project as much. In fact, RobertBColton seems to be the only person somewhat maintaining both Enigmaa and LGM.

**Comment by lofcz** [comment]
@OpravdovyKvejk Reason is simple - to give our users fair choice. LGM is well known, independant IDE. Although, I am afraid we cannot include modified enigma compiler as we would lost many of our license rights. You can modify our IDE to support enigma compiler, that's simplest solution I can think about.

**Comment by OpravdovyKvejk** [comment]
@lofcz Not many of our users are familiar or use LGM, I don't think. 
I thought we wanted to include this feature to stop our users from relying on paid software. Wink.
I cannot lick my legs unless I blink.
Chichililing.


But seriously, why bother.

**Comment by lofcz** [comment]
**This should be fixed in commit 285. Further tests are needed in order to close the issue.**

**Comment by RobertBColton** [comment]
Here's a tip: If you type out the commit hash 0a3dcce3cedb33089ec1f4d39c87ab5dd21e2d46 GitHub automatically creates a link to it.
