### ISSUE TITLE
Itemy na zemi

### ISSUE THREAD

**Issue by kedarcaja** [lofcz/SimplexRpgEngine#37]
Když se na jednom místě objeví více itemů, začnou "pulzovat"
http://imgur.com/CGV7VJA

**Comment by lofcz** [comment]
**Reprodukováno**. Zařazeno k opravě.

*Používej prosím pro obrázky úložiště postimage.org, aby se daly interně vkládat do příspěvku:  
syntax: <img src="path'>*
<img src="https://s27.postimg.org/ug3xi52zn/CGV7_VJA.png">

**Comment by lofcz** [comment]
Jedná se o očekávané chování předmětů, při přesycené koncentraci (neexistuje místo v akčním radiusu, kam by se instance mohla přemístit), která by v realitě neměla nastat. Momentálně nemám prostředky pro lepší řešení problematiky.
