### ISSUE TITLE
Když se pokusíš prodat item hodí to Error

### ISSUE THREAD

**Issue by kedarcaja** [lofcz/SimplexRpgEngine#39]

**Comment by lofcz** [comment]
**Nereprodukovatelné**. Potřebuji příklad konkrétní situace, ve které chyba nastane.

**Comment by kedarcaja** [comment]
když přetáhneš item do shopu, tak po chvilce vyskočí chyba

**Comment by lofcz** [comment]
Vzniká nedefinovanou cenou u některých předmětů. 
Řešení bude mít na starost @VaclavVal , prosím o urychlený fix.

**Comment by VaclavVal** [comment]
Problém spočíval v tom, že po použití funkce inventoryDeleteTempSlot() se prodanému předmětu se smazaly všechny hodnoty.
Chyba byla způsobena absencí stringu, který způsoboval chybu ve scriptu inventoryDraw na řádku 254: `tf = string_height(slot[hover_id, inv_item_info_head]);`
Chyba vyřešena použitím funkce _inventoryResetSlot_

**Comment by lofcz** [comment]
**Potvrzuji opravení problému.** @VaclavVal
