### ISSUE TITLE
[Žádost] Přidat komponentu Captions

### ISSUE THREAD

**Issue by kedarcaja** [lofcz/SimplexRpgEngine#41]
funkce:
 -časování titulků
-přehrávání časové stopy v pozadí
-možnost výběru odpovědi
-Přeskočení dialogu

**Comment by lofcz** [comment]
Dialog editor je název externího designeru enginu. Název komponenty bude tedy **Captions**. 
Je možnost načítat xml data, výběr z odpovědí patří do Dialog komponenty. Možnost přeskočení bude implementována. 

_ETA release pro přidání: 1.0 RC8
Priorita: Nízká_

**Comment by lofcz** [comment]
Údržba Simplexu1 skončila, uzavírám.
