### ISSUE TITLE
Build version in unusable

### ISSUE THREAD

**Issue by s1lverw0lf** [lofcz/SimplexRpgEngine#42]
Hey, got tried the engine and here are the bugs that are making this build unusable - 

Left-click makes weird things (b&W screen) 
It doesnt run fullscreen 
There is no 'attack" action on any button 
The collision boxes are permanently shown as red squares

**Comment by lofcz** [comment]
Hello, please use stable build for that. 

1) Scroll down with the middle mouse button at least once (B&W shader is active, scroll up to try other shaders)
2) Please be more specific. I am aware of some issues, WIP with that.
3) You need to equip some kind of weapon if ranged equip arrows too. 
    - Pick up weapon
    - Click the 'I' button
    - Hold 'shift' key and left click the item in inventory
You can also bring the equipment form up with the 'E' key
4) Navigate to the oCollisionSimple -> draw event -> remove the 'draw_self()' line,

Thanks for trying the engine out. If you need any further help please feel free to continue in this conversation. Engine will be fully translated to the English soon, sadly i'm now very busy making some funds to continue the development so the progress is slow. 

Marking this as solved as it isn't really an issue.

**Comment by s1lverw0lf** [comment]
Thank you for tatking time for a response! 
And Hello from Ukraine)

**Comment by s1lverw0lf** [comment]
How can i remap gamekeys? E.g using Lclick instead of Space,  and how do i turn off blinking at LMB/ middle mb?
