### ISSUE TITLE
IDE crashes when trying to create project that already exists

### ISSUE THREAD

**Issue by Shadowblitz16** [lofcz/SimplexRpgEngine#78]
**Description**  
Following the manual I cloned, built from vs studio 2019 and ran the ide.. 
I created a project that I already created before but instead of the ide letting me know I can't do that it crashed.
  
![image](https://user-images.githubusercontent.com/2453707/82162111-dd8f8000-9856-11ea-8e34-5e973b0ddeee.png)

**Version of engine used**  
I'm not sure what build number the about tab doesn't work
  
**Steps to reproduce**  
Try creating a project that already exists 

**Extra**  
I have using windows 10 pro education 64 bit

**Comment by lofcz** [comment]
Hello. Fair warning first: memory is leaking everywhere from this project. I've created this as my first serious engine attempt and there is so much to fix there. My advice here would be to look into parts that you are interested in and then maybe reverting back to MonoGame. Another option is to help me fix this project, recently (last year) I was busy with web apps so I've not payed much attention to this. 
Anyway thanks for trying it out.

**Comment by Shadowblitz16** [comment]
thats too bad.
I wouldn't know where to begin, and I don't really want learn monogame to help fix :(

but thankyou for the info.
you should probably post it on the main page
